name: Mark stale issues
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: "This issue has been marked as stale due to inactivity."
          stale-pr-message: "This PR has been marked as stale due to inactivity."
          exempt-issue-labels: "pinned,security"
